// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9nXKbWHyc6Lh2uvXPhOPj1i48y_S9no',
    appId: '1:620429005943:web:b83f38d414f501e8aae272',
    messagingSenderId: '620429005943',
    projectId: 'spot-3215b',
    authDomain: 'spot-3215b.firebaseapp.com',
    storageBucket: 'spot-3215b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9WcTxMVLllteSIgkU-aiaudhQH6D0Yw',
    appId: '1:620429005943:android:4112fead96a5442eaae272',
    messagingSenderId: '620429005943',
    projectId: 'spot-3215b',
    storageBucket: 'spot-3215b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC89PZlH9enF884Jyxwq65AMtpFIhpKknc',
    appId: '1:620429005943:ios:5f03f7f628152b51aae272',
    messagingSenderId: '620429005943',
    projectId: 'spot-3215b',
    storageBucket: 'spot-3215b.appspot.com',
    iosClientId: '620429005943-olj1hlqvcis81nqtqmmck8rickrb7ij0.apps.googleusercontent.com',
    iosBundleId: 'com.example.spot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC89PZlH9enF884Jyxwq65AMtpFIhpKknc',
    appId: '1:620429005943:ios:5f03f7f628152b51aae272',
    messagingSenderId: '620429005943',
    projectId: 'spot-3215b',
    storageBucket: 'spot-3215b.appspot.com',
    iosClientId: '620429005943-olj1hlqvcis81nqtqmmck8rickrb7ij0.apps.googleusercontent.com',
    iosBundleId: 'com.example.spot',
  );
}
